---
- name: Configure Web Server
  hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
    # Add more tasks as needed for Web Server setup (e.g., install Apache2, WordPress)

